import type { Metadata } from 'next'
import { PageHeader } from '@/components/page-header'
import { breadcrumbSchema } from '@/lib/schema'
import { siteConfig } from '@/lib/site-config'

export const metadata: Metadata = { title: 'Politique de confidentialité', robots: { index: false, follow: true }, alternates: { canonical: '/politique-de-confidentialite' } }

export default function PrivacyPage() {
  return <div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema([{ name: 'Accueil', path: '/' }, { name: 'Confidentialité', path: '/politique-de-confidentialite' }])) }} /><PageHeader eyebrow="Vos données" title="Politique de confidentialité" description="Nous vous expliquons clairement quelles données sont recueillies et comment elles sont utilisées." breadcrumb="Confidentialité" /><section className="section-space"><div className="legal-copy mx-auto max-w-3xl space-y-4 px-5 text-sm leading-8 text-muted-foreground sm:px-8"><div><h2>Données collectées</h2><p>Lorsque vous envoyez une demande, nous recueillons les informations que vous fournissez, comme votre nom, votre e-mail, votre téléphone et les détails du projet. Elles sont utilisées uniquement pour étudier votre demande et vous recontacter.</p></div><div><h2>Mesure d&apos;audience</h2><p>Ce site utilise Vercel Analytics pour obtenir des statistiques de visite globales et anonymes. Cet outil n&apos;est pas conçu pour identifier personnellement les visiteurs.</p></div><div><h2>Conservation et destinataires</h2><p>Les informations du formulaire sont transmises directement au studio et ne sont pas partagées à des fins commerciales. Elles sont conservées uniquement pendant la durée nécessaire au traitement de votre demande.</p></div><div><h2>Vos droits</h2><p>Conformément au RGPD, vous disposez d&apos;un droit d&apos;accès, de rectification et de suppression. Pour exercer ce droit, contactez le studio au {siteConfig.phoneDisplay}.</p></div><div><h2>Cookies</h2><p>Des cookies techniques indispensables peuvent être utilisés. Aucun cookie publicitaire ou de suivi tiers n&apos;est activé sans votre accord.</p></div></div></section></div>
}
